[toolchain]
channel = "nightly-2025-03-28"
components = [ "rustfmt", "rustc-dev" ]
# targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ] # host target triple is included by default
profile = "minimal"
